# Generated by Django 2.0.5 on 2018-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mailbox', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
