# Generated by Django 2.0.5 on 2018-11-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('size', models.CharField(max_length=10)),
                ('url', models.CharField(default='/', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.CharField(max_length=20)),
                ('oDate', models.DateField()),
                ('status', models.IntegerField()),
                ('fileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysite.File')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('parent_dir', models.CharField(default='Home', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mailbox', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fileuser',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysite.User'),
        ),
        migrations.AlterUniqueTogether(
            name='fileuser',
            unique_together={('userId', 'fileId')},
        ),
    ]
