# Generated by Django 2.0.5 on 2018-10-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('size', models.CharField(max_length=10)),
                ('parent_dir', models.CharField(default='Home', max_length=30)),
                ('url', models.CharField(default='/', max_length=250)),
            ],
        ),
    ]
