# Generated by Django 2.0.5 on 2018-10-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysite', '0002_auto_20181025_1838'),
    ]

    operations = [
    ]
