# Generated by Django 2.0.5 on 2018-10-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysite', '0003_auto_20181025_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('size', models.CharField(max_length=10)),
            ],
        ),
    ]
