# Generated by Django 2.0.5 on 2018-10-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysite', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent_dir',
            field=models.CharField(default='/', max_length=30),
            preserve_default=False,
        ),
    ]
