# Generated by Django 2.0.5 on 2018-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysite', '0005_file_parent_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent_dir',
            field=models.CharField(default='Home', max_length=30),
        ),
    ]
